version: '3.7'
services:

    postgres:
        image: postgres:12-alpine
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - ~/docker/postgres-data/init.d:/docker-entrypoint-initdb.d
            - ~/docker/postgres-data/data:/var/lib/postgresql/data
            - ~/docker/postgres-data/servers.json:/tmp/servers.json
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
            PGADMIN_SERVER_JSON_FILE: /tmp/servers.json
        hostname: postgres
        restart: always
        user: root

    pgadmin4:
        image: dpage/pgadmin4:4.2
        container_name: pgadmin4
        ports:
            - 8000:80
        volumes:
            - ~/docker/postgres-data/pgadmin4:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: root
            PGADMIN_DEFAULT_PASSWORD: root
        hostname: pgadmin4
        depends_on:
          - postgres
        restart: always
