version: '3.3'
services:

    postgis:
        image: postgis:11.3
        container_name: postgis
        ports:
            - 5432:5432
        volumes:
           - ~/docker/docker-compose/mount/init.d:/docker-entrypoint-initdb.d
           - ~/docker/docker-compose/mount/data:/var/lib/postgresql/data
           - ~/docker/docker-compose/mount//servers.json:/tmp/servers.js
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        hostname: postgis
        restart: always
        user: root

    pgadmin4:
        image: dpage/pgadmin4:4.19
        container_name: pgadmin4
        ports:
            - 8000:80
        volumes:
            - ~/docker/docker-compose/mount/pgadmin4:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin
            PGADMIN_DEFAULT_PASSWORD: admin
        hostname: pgadmin4
        depends_on:
          - postgis
        restart: always
        user: root

    geoserver:
        image: geonode/geoserver
        container_name: geoserver
        ports:
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/docker/docker-compose/mount/geoserver/data/:/geoserver_data/data
        hostname: geoserver
        restart: always
        user: root
        
