version: '3'
services:
  arcgis-anaconda:
    build:
      context: .
      dockerfile: Dockerfile
    image: anaconda3_arcgis:1.62_post
    ports:
    - "8888:8888"
    volumes:
    - ./data:/workdir